### ISSUE TITLE
Remove staff from slow response accounting

### ISSUE THREAD

**Issue by autonome** [ipfs-shipyard/ecosystem-dashboard#109]
Staff often file issues and of course know those issues are there, and don't need to respond to their own issues (or have other venues like their regular meetings, etc).

The metric for slow responses is for healthy community engagement and participation, so PL staff should be removed.

**Comment by andrew** [comment]
@autonome have you got an example issuse/pr or screenshot?

**Comment by autonome** [comment]
aarghghg now i can't find it 😐
