### ISSUE TITLE
Collab RSS feed not fully updated

### ISSUE THREAD

**Issue by dchoi27** [ipfs-shipyard/ecosystem-dashboard#111]
The RSS feed [here](https://ecosystem-research.herokuapp.com/collabs.rss) doesn't reflect the orgs shown [here](https://ecosystem-research.herokuapp.com/collabs). The RSS feed for the active collabs looks right, though.

Edit: Also the case for the repositories feed [here](https://ecosystem-research.herokuapp.com/collabs/repositories.rss) - this one would be the most useful to have for activity tracking in downstream repositories (don't even need the RSS feed itself - just a way to scrape the repositories shown [here](https://ecosystem-research.herokuapp.com/collabs/repositories) to track)

**Comment by andrew** [comment]
@dchoi27 looks like the rss feed was only showing the first 20 results where as the html page had 100, I've bumped up the per_page limit on the rss feed to 1000 so you should be able to get them all in a single request.

**Comment by dchoi27** [comment]
Thank you!
