### ISSUE TITLE
Add a new "slowish responses" which is 96hrs instead of 48hrs

### ISSUE THREAD

**Issue by autonome** [ipfs-shipyard/ecosystem-dashboard#168]
Or maybe just rearchitect with a way to pass in the internal as a param. Eg, if you store opened-time we could pass in -48 or -96 or -1 to get issues unresponded to in that time period?

**Comment by andrew** [comment]
Turns out the response time is stored in seconds in the database it can be configured as a url parameter 🎉

**Comment by andrew** [comment]
Shipped it as an option: https://ipfs.ecosystem-dashboard.com/slow_response?slowish_response=true 

Drop down menu from slow responses page, you can also add `?slowish_response=true` parameter to your existing rss feed and it'll increase it to 96 hours.

![Screenshot 2021-03-16 at 11 19 15](https://user-images.githubusercontent.com/1060/111300869-73e42c00-8649-11eb-8b7a-5f27676e84d0.png)
