### ISSUE TITLE
Add ability to do repo lookups for usage of ipfs/filecoin/libp2p/ipld/etc

### ISSUE THREAD

**Issue by autonome** [ipfs-shipyard/ecosystem-dashboard#173]
Like https://ipfs.ecosystem-dashboard.com/pmf/repositories?names=foo/bar

But where foo/bar repository is not yet known to us.

MVP: for one repo, respond with whether or not it uses our technologies at the project level, and which ones

Better: accept multiple input names

Bestester: trawl the extended dep graph and see if our stuff is in there somewhere

**Comment by andrew** [comment]
🚢 https://ipfs.ecosystem-dashboard.com/discover 

![Screenshot 2021-03-26 at 14 25 46](https://user-images.githubusercontent.com/1060/112646303-3ea4be80-8e3f-11eb-8f2b-849bc87088d8.png)
