### ISSUE TITLE
Add ability to filter to core contributors

### ISSUE THREAD

**Issue by BigLep** [ipfs-shipyard/ecosystem-dashboard#184]
PL usecase: during weekly triage we like to sometimes filter to PRs that have been submitted by PL core contributors.  

I hoped I could add something like "only_core=true" or "&exclude_collabs=true&exclude_community=true", but doesn't appear to work.

I didn't dig too deep, but quick search of https://github.com/ipfs-shipyard/ecosystem-dashboard/search?q=core didn't yield anything.

**Comment by andrew** [comment]
I hooked up `only_core=true` to work as expected, it'll also be present in the Extras dropdown menu once it's deployed in a few minutes:
![Screenshot 2021-04-08 at 16 28 06](https://user-images.githubusercontent.com/1060/114054129-7bcd6f80-9887-11eb-866d-5db2530b1289.png)

**Comment by andrew** [comment]
Example url: https://ipfs.ecosystem-dashboard.com/all?only_core=true&range=30
