### ISSUE TITLE
Add ability to filter issues that aren't on a project board

### ISSUE THREAD

**Issue by BigLep** [ipfs-shipyard/ecosystem-dashboard#185]
During PL weekly triage, we moved certain issues to PL project boards (see below).  It would be ideal if we could construct ecosystem dashboard links that filtered out whether an issue was already on a board.  Even better would be if we could filter whether it was on a specific board, but even a simple binary "is it on or not no a board" is good enough for now.

IPFS: https://github.com/orgs/ipfs/projects/12
libp2p: https://github.com/orgs/libp2p/projects/1
IPLD: https://github.com/orgs/ipld/projects/1
Multiformats: https://github.com/orgs/multiformats/projects/1

**Comment by andrew** [comment]
We can see some project details in the [issue timeline api](https://docs.github.com/en/rest/reference/issues#list-issue-events):

```
 :project_card=>
  {:id=>58139620,
   :url=>"https://api.github.com/projects/columns/cards/58139620",
   :project_id=>12105538,
   :project_url=>"https://api.github.com/projects/12105538",
   :column_name=>"BackLog"}
```

So I think we can store the project_id on an issue then provide a filter for issues with no project id

**Comment by andrew** [comment]
Deploying a first pass that will enable filtering by "on any project board", will need to resync all the issues to update the new field so may take a little while for everything to catch up.

To be able to give a full list of boards for each issue we'll need to tweak the permissions on the ecosystem oauth token as I get this error using the graphql api:

```
Although you appear to have the correct authorization credentials, the `filecoin-project` organization has enabled OAuth App access restrictions, meaning that data access to third-parties is limited. For more information on these restrictions, including how to enable this app, visit https://docs.github.com/articles/restricting-access-to-your-organization-s-data/
```

In theory we can use a graphql query like this:

```
{
  repository(name: "venus", owner: "filecoin-project") {
    issue(number: 4381) {
      title
      projectCards {
        nodes {
          createdAt
          column {
            name
          }
          project {
            name
            body
            id
          }
        }
      }
    }
  }
}
```

**Comment by andrew** [comment]
Added a label if the issue belongs to one or more boards:
![Screenshot 2021-04-08 at 17 16 40](https://user-images.githubusercontent.com/1060/114061312-3496ad00-988e-11eb-9c7c-5f7861b9b8e4.png)

**Comment by andrew** [comment]
Deploying a filter now for "Not on any boards": http://ipfs.ecosystem-dashboard.com/all?no_boards=true

![Screenshot 2021-04-08 at 17 20 20](https://user-images.githubusercontent.com/1060/114062129-10879b80-988f-11eb-8b93-71da53363dcb.png)

**Comment by andrew** [comment]
I've kicked off a syncing task for all issues opened in the past 6 months, if we need to go further back than that then let me know.
