### ISSUE TITLE
Ability force refresh of an issue

### ISSUE THREAD

**Issue by BigLep** [ipfs-shipyard/ecosystem-dashboard#187]
When labels get added to older issues, we've observed that that metadata doesn't propagate through (e.g., https://github.com/ipfs/go-datastore/issues/160 ).  When we notice this, could there be a self-service way to force a metadata sync?

I know you've also discussed that we could set up webhooks for all pl repos to tell the ecosystem dashboard when anything changes so all issues would be updated within seconds of a change (but that requires someone with admin permissions on the gh repos).  If you feel it would be a better use of your time to pursue that path, I'm happy to work through the permissions stuff.

**Comment by andrew** [comment]
![Screenshot 2021-04-12 at 16 44 54](https://user-images.githubusercontent.com/1060/114422744-75eccc80-9bae-11eb-9316-d7c9b9967b3d.png)

Deploying a sync button on all issues now
