### ISSUE TITLE
Add IP core contributors

### ISSUE THREAD

**Issue by BigLep** [ipfs-shipyard/ecosystem-dashboard#188]
While triaging IP issues, we noticed these folks weren't coming through as core contributors:
@web3-bot
@gammazero

Can they please be added?

This was discovered in this link: https://ecosystem-research.herokuapp.com/all?sort=updated_at&order=asc&range=90&state=open&per_page=100&exclude_org%5B%5D=ipfs-shipyard&exclude_org%5B%5D=ProtoSchool&exclude_org%5B%5D=ChainSafe&exclude_org%5B%5D=NodeFactoryIo&no_boards=true&language=Go&community=true&exclude_core=true&type=pull_requests

**Comment by andrew** [comment]
Done!
