### ISSUE TITLE
Manual "sync" isn't working in some cases

### ISSUE THREAD

**Issue by BigLep** [ipfs-shipyard/ecosystem-dashboard#201]
https://github.com/libp2p/js-libp2p-relay-server/pull/2 is closed.

It keeps showing up in https://ecosystem-research.herokuapp.com/all?sort=updated_at&order=asc&range=180&state=open&per_page=100&exclude_org%5B%5D=ipfs-shipyard&exclude_org%5B%5D=ProtoSchool&exclude_org%5B%5D=ChainSafe&exclude_org%5B%5D=NodeFactoryIo&no_boards=true&language=JS&only_core=true&type=pull_requests 

I have manually synced it (hitting https://ecosystem-research.herokuapp.com/issues/304422/sync ) but it still shows up.

**Comment by andrew** [comment]
Looks like it got a bit confused over the repo being renamed and ended up with a duplicate, which then didn't get updated correctly, I've cleaned that out, will add a catch for it next week, will close this once it's done.

**Comment by lidel** [comment]
I see the same problem with issues from  ipfs-desktop, ipfs-companion, ipfs-webui, ipld-explorer-components and  explore.ipld.io, which were moved recently between orgs. Closes issues are still listed on: 

https://ecosystem-research.herokuapp.com/all?label%5B%5D=need%2Ftriage&order=asc&per_page=100type%3Dissues&range=365&repo_full_name%5B%5D=ipfs%2Fipfs-webui&repo_full_name%5B%5D=ipfs%2Fipfs-desktop&repo_full_name%5B%5D=ipfs-shipyard%2Fipfs-desktop&repo_full_name%5B%5D=ipfs-shipyard%2Fipfs-webui&repo_full_name%5B%5D=ipfs%2Fipfs-companion&repo_full_name%5B%5D=ipfs%2Fin-web-browsers&repo_full_name%5B%5D=ipfs-shipyard%2Fipfs-share-files&repo_full_name%5B%5D=ipld%2Fexplore.ipld.io&repo_full_name%5B%5D=ipfs%2Fipld-explorer-components&repo_full_name%5B%5D=ipfs%2Fdir-index-html&repo_full_name%5B%5D=ipfs%2Fexplore.ipld.io&repo_full_name%5B%5D=ipfs%2Fpublic-gateway-checker&repo_full_name%5B%5D=ipfs-shipyard%2Fipfs-companion&repo_full_name%5B%5D=ipfs-shipyard%2Fipfs-css&repo_full_name%5B%5D=ipfs%2Fdistributions&repo_full_name%5B%5D=ipfs%2Fipfs-gui&repo_full_name%5B%5D=ipfs-shipyard%2Fi18n&repo_full_name%5B%5D=ipfs-shipyard%2Fipfs-ui-style-guide&sort=updated_at&state=open

and clicking sync button does not seem to help.

**Comment by lidel** [comment]
I think we need a generic support for "detecting" moved repos. We do move things  from time to time and not handling it means links to our triage boards erode over time, and we may miss some issues. 

Github redirects some things, but not everything. I think heuristic would  be to detect  "missing repo" errors when interacting with API, and then check if the repo was renamed by making request to `github.com/{repo-name}` and checking if there is a redirect in `Location` header. If the header is present, retry API request with new name.

**Comment by andrew** [comment]
@lidel I'll get those fixed up, ecosystem dashboard handles the renames/redirects properly but it's getting duplicates which then can't be written back into the database due to the unique index.

**Comment by andrew** [comment]
I've deployed a small tweak that cleans up duplicates upon syncing which unblocks this, I'm also going to run a script that goes through and syncs all existing open issues that may be duplicated to save you pressing the sync button hundreds of times!

**Comment by andrew** [comment]
@lidel that list should all be up to date now.
