### ISSUE TITLE
add detection of solidity files in github repos, so we can track smart contract + (our stuff) projects

### ISSUE THREAD

**Issue by autonome** [ipfs-shipyard/ecosystem-dashboard#203]

**Comment by andrew** [comment]
Do you want to store a flag if there is one ore more .sol files or a list of every .sol file?

**Comment by autonome** [comment]
Good question.

Storing a flag gets us "is a dapp".

Storing URL to file gets us "is a dapp", and ability to do some things
later if we want.

But I don't know what those things are, and none that I can think of are
germane to our primary goals in this work.

Also, since we run these periodically, we could always add the latter later.

So let's just do a flag.

**Comment by andrew** [comment]
Deploying the boolean version now (field is called `sol_files` on the `repositories` table), it may take a couple days for all repos to be reindexed.

**Comment by andrew** [comment]
Need to add a filter to the UI as the data isn't being warehoused anymore, will keep this open for now.

**Comment by andrew** [comment]
Filter added: https://ipfs.ecosystem-dashboard.com/community/repositories?per_page=20&smart=true 

![Screenshot 2021-05-06 at 09 54 06](https://user-images.githubusercontent.com/1060/117270338-04243d80-ae51-11eb-88da-64c05adec2c4.png)
