### ISSUE TITLE
Is data stale?

### ISSUE THREAD

**Issue by BigLep** [ipfs-shipyard/ecosystem-dashboard#297]
During triage today (2021-11-12), we were often seeing less issues/PRs than we'd expect.  I'll dig up more examples, but this URL seems to show it:

https://ecosystem-research.herokuapp.com/all?exclude_core=true&range=365&type=issues

This seems off.  Only 2 issues? (I wish!)
![image](https://user-images.githubusercontent.com/85411/141599687-1d88c4ec-058e-4b99-8fe5-a676d0fbc531.png)

**Comment by andrew** [comment]
I did notice rate limits were being hit much more frequently the past couple weeks, will need to make some changes to ensure we can still load data, will tackle on Monday

**Comment by andrew** [comment]
Apologies, it wasn't related to rate limiting but an unintended side effect of creating a database record for every contributor, which hid non-core contributions from the UI. 

All the data is still there, just deploying a couple of fixes now to get it all showing up again.

**Comment by BigLep** [comment]
Hi @andrew - thanks for looking and for the update.  Not sure if your fixes were deployed, but I'm seeing more links that we use in triage where we look to be missing data:

js core PRs: https://ecosystem-research.herokuapp.com/all?state=open&per_page=100&sort=updated_at&order=asc&exclude_org%5B%5D=ipfs-shipyard&exclude_org%5B%5D=nftstorage&exclude_org%5B%5D=web3-storage&exclude_org%5B%5D=ProtoSchool&exclude_org%5B%5D=ChainSafe&exclude_org%5B%5D=NodeFactoryIo&exclude_repo_full_name%5B%5D=libp2p%2Fgo-smart-record&range=180&no_boards=true&language=JS&only_core=true&type=pull_requests

js community PRs: https://ecosystem-research.herokuapp.com/all?state=open&per_page=100&sort=updated_at&order=asc&exclude_org%5B%5D=ipfs-shipyard&exclude_org%5B%5D=nftstorage&exclude_org%5B%5D=web3-storage&exclude_org%5B%5D=ProtoSchool&exclude_org%5B%5D=ChainSafe&exclude_org%5B%5D=NodeFactoryIo&exclude_repo_full_name%5B%5D=libp2p%2Fgo-smart-record&range=180&no_boards=true&language=JS&community=true&exclude_core=true&type=pull_requests

**Comment by andrew** [comment]
@BigLep can you share issues/prs that you expect to see on those links that aren't there, as far as I can tell those two links are showing the correct data (the "not on any boards" filter applied there is hiding a lot of prs)

**Comment by BigLep** [comment]
@andrew : my bad, I don't have an example that shows things aren't working.  I'll reopen if I find anything.  Thanks!
