### ISSUE TITLE
Shouldn't pull from archived repos

### ISSUE THREAD

**Issue by autonome** [ipfs-shipyard/ecosystem-dashboard#30]
Ran into this in triage with https://github.com/libp2p/js-libp2p-websocket-star-rendezvous/issues/34

**Comment by andrew** [comment]
@autonome do you have the url that it showed up in? Issues+PRs in archived repos shouldn't be showing up anywhere

**Comment by andrew** [comment]
I found a few issues that were out of sync, will make a note to ensure if repos are detected as becoming archived that all issues should be resynced so that they disappear.

**Comment by autonome** [comment]
https://ecosystem-research.herokuapp.com/all?exclude_employees=true&language=JS&no_response=true&order=asc&sort=updated_at&state=open

**Comment by autonome** [comment]
awesome, thanks!

**Comment by andrew** [comment]
The dashboard should now correctly handle repos being archived or unarchived and show/hide all issues and PRs correctly.
