### ISSUE TITLE
I have a local version running, but there doesn't seem to be any data

### ISSUE THREAD

**Issue by SgtPooki** [ipfs-shipyard/ecosystem-dashboard#376]
I've added organizations via 

```bash
org = Organization.create(name: GITHUB_ORG_NAME, internal: true)
org.import
# and
org = Organization.create(name: GITHUB_ORG_NAME, collaborator: true)
org.import
```

my ecosystem-research db is still empty for some reason, or at least appears that way in the UI.

* http://localhost:3000/collabs shows ipfs-shipyard and ipfs, but shows 0 activity
* http://localhost:3000/orgs/ipfs-shipyard shows 45 repos
* http://localhost:3000/collabs/repositories?order=desc&org=ipfs-shipyard&sort=created_at doesn’t list any repos "no items found"
* localhost:3000/repositories doesn't list any repositories.
* http://localhost:3000/sidekiq history section says 0 failed, 0 processed
* http://localhost:3000/sidekiq/queues shows a 'default' queue with size 417

**Comment by SgtPooki** [comment]
I was able to kick off the jobs with `bundle exec sidekiq`.. waiting to see if any data appears after these jobs process.

**Comment by SgtPooki** [comment]
sidekiq is done running the jobs in the queue, 
![image](https://user-images.githubusercontent.com/1173416/155394675-accad76c-3dcb-4ed7-b2c1-dbe0bc13e3f0.png)
but there is still no data showing on repositories or issues/prs:
![image](https://user-images.githubusercontent.com/1173416/155395888-44bc19e4-442a-4f46-add6-e266d296bd09.png)
![image](https://user-images.githubusercontent.com/1173416/155395927-1e793904-9a2a-4bcb-9dad-7a296874c608.png)
![image](https://user-images.githubusercontent.com/1173416/155396055-8ebc879a-61a1-4dad-822e-b735d0c82cee.png)


## Collabs/events does show some events: 
![image](https://user-images.githubusercontent.com/1173416/155396224-c6e3a560-418e-4847-9b00-c40efbc9ec2d.png)

**Comment by andrew** [comment]
`org.import` should do the majority of the work but could well be failing due to hitting a github rate limit (i see 186 failed jobs in your sidekiq screenshot).

As a follow up you could run: `Organization.each(&:sync_recently_active_repos)`
to pull in some of the newest data.

I wouldn't expect to see any data in urls with `/collabs` in them unless you have made some collab orgs `Organization.create(name: 'textileio', collaborator: true)`

**Comment by andrew** [comment]
👍
