### ISSUE TITLE
"Not on any boards" filter isn't consistently working

### ISSUE THREAD

**Issue by BigLep** [ipfs-shipyard/ecosystem-dashboard#390]
As part of go-ipfs triage we use the "not on any boards" filter extensively.

Example triage URL: https://ecosystem-research.herokuapp.com/all?org=ipfs&exclude_language%5B%5D=JavaScript&exclude_language%5B%5D=TypeScript&exclude_repo_full_name%5B%5D=ipfs%2Fipfs-companion&exclude_repo_full_name%5B%5D=ipfs%2Fipfs-desktop&exclude_repo_full_name%5B%5D=ipfs%2Fipfs-webui&exclude_repo_full_name%5B%5D=ipfs%2Fpublic-gateway-checker&exclude_repo_full_name%5B%5D=ipfs%2Fipfs-update&exclude_repo_full_name%5B%5D=ipfs%2Fawesome-ipfs&exclude_repo_full_name%5B%5D=ipfs%2Fcommunity&exclude_repo_full_name%5B%5D=ipfs%2Fdevgrants&exclude_repo_full_name%5B%5D=ipfs%2Fecosystem-directory&exclude_repo_full_name%5B%5D=ipfs%2Fipfs-website&exclude_repo_full_name%5B%5D=ipfs%2Fipfs-blog&exclude_repo_full_name%5B%5D=ipfs%2Fipfs-cluster&exclude_repo_full_name%5B%5D=ipfs%2Fgo-graphsync&exclude_repo_full_name%5B%5D=ipfs%2Fpinning-services-api-spec&exclude_repo_full_name%5B%5D=ipfs%2Fdistributions&exclude_repo_full_name%5B%5D=ipfs%2Fdistributed-wikipedia-mirror&exclude_repo_full_name%5B%5D=ipfs%2Fin-web-browsers&exclude_repo_full_name%5B%5D=ipfs%2Fjs-ipfs&exclude_repo_full_name%5B%5D=ipfs%2Faegir&range=360&state=open&per_page=100&sort=updated_at&order=desc&no_boards=true&community=true&exclude_core=true&type=pull_requests

As an example, this issue shows up: https://github.com/ipfs/go-ipfs/pull/8806

It is on a board though: 
<img width="329" alt="image" src="https://user-images.githubusercontent.com/85411/160625585-ca1e91eb-69d4-45fb-905d-31a467ed978c.png">

A couple of things:
1. I have tried "refreshing" the issue in the ecosystem dashboard.  That didn't change anything.
2. We did more recently move to the new beta project boards in case that is affecting things.
3. This isn't consistent.  We do so many things get filtered out with the "not on any boards" filter.  I haven't found a pattern as to why.

**Comment by andrew** [comment]
Looks like GitHub have changed something (could be the beta you mentioned) that has stopped generating events for when an issue/pull is added to a board, which was how it was detected before. I'll need to find another way to check if an issue has been added to a board

**Comment by andrew** [comment]
There's definitely event data missing from the github rest api, I suspect i'll need to use the graphql api to get the board ids instead.

**Comment by BigLep** [comment]
@andrew : thanks for the response.  Is API Token fetching something you would like me to help with?

I think you can make the request in the PLN Pathfinder (IT Support) Discord server: https://discord.gg/KUgWC5Te

**Comment by andrew** [comment]
@BigLep that discord link didn't work for me, can you resend or ping me on slack?

**Comment by BigLep** [comment]
@andrew : any luck here?  Let me know if there's a thread with Pathfinder I should followup on or give my support in.

**Comment by andrew** [comment]
@BigLep pinged you in discord

**Comment by andrew** [comment]
This should be working for all boards owned by the `ipfs` org now, the 'sync' button on each issue should update the board_ids field now too.

**Comment by BigLep** [comment]
Hi @andrew .  I can confirm it's working for IPFS.  Can you please also do it for IPLD and libp2p?

**Comment by BigLep** [comment]
ACK.  I have made the membership requests here.  Once those are merged you should be unblocked.
https://github.com/libp2p/github-mgmt/pull/8
https://github.com/ipld/github-mgmt/pull/7

**Comment by andrew** [comment]
I’m in both orgs now, IPLD already approved the oauth app, libp2p approval requested

**Comment by andrew** [comment]
Still waiting for libp2p approval:
<img width="880" alt="Screenshot 2022-05-16 at 09 51 01" src="https://user-images.githubusercontent.com/1060/168555377-dea8f4b0-9658-4e3d-9dc2-7ae415d1169c.png">

I've resynced all the ipld issues as well, let me know if anything isn't looking right

**Comment by BigLep** [comment]
@marten-seemann or @mxinden: can you please approve Anderw's oath request for libp2p?  It will allow during triage for us to filter out issues that are already on a new github project board.

I think you can find the link to approve it here: https://github.com/organizations/libp2p/settings/oauth_application_policy

**Comment by marten-seemann** [comment]
Done.

**Comment by andrew** [comment]
Thanks, will get the libp2p issues resynced first thing tomorrow

**Comment by andrew** [comment]
Synced up the libp2p issues, let me know if there's anything else looking right

**Comment by BigLep** [comment]
Thanks.  I'll check during week of 2022-05-23.

**Comment by BigLep** [comment]
@andrew : during 2022-05-27 triage, this item showed up https://github.com/libp2p/go-libp2p-core/pull/234 event though it was already on a board and we are filtering out issues on a board.

**Comment by andrew** [comment]
Found and fixed a bug with syncing boards, synced https://github.com/libp2p/go-libp2p-core/pull/234 myself and it's now correctly being filtered out

**Comment by BigLep** [comment]
@andrew : I think we're good to close this now, right?

**Comment by andrew** [comment]
Yep
