### ISSUE TITLE
Language filters aren't fully filtering

### ISSUE THREAD

**Issue by BigLep** [ipfs-shipyard/ecosystem-dashboard#392]
For some of PL EngRes triage, we like to filter out a language like "JavaScript" and "TypeScript".

Using a URL like this: https://ecosystem-research.herokuapp.com/all?org=ipfs&exclude_language%5B%5D=JavaScript&exclude_language%5B%5D=TypeScript&range=360&state=open&per_page=100&sort=updated_at&order=desc&no_boards=true&community=true&exclude_core=true&type=pull_requests

I still see issues from repos I wouldn't expect like js-ipfs, aegir, etc.

Example: https://github.com/ipfs/js-ipfs/pull/4073

js-ipfs is listed as only being JavaScript and TypeScript at https://github.com/ipfs/js-ipfs
<img width="328" alt="image" src="https://user-images.githubusercontent.com/85411/160627793-fb4a0493-7427-45bb-90d8-f8eb56da1e26.png">

Is this a bug or is there extra language metadata that is being grabbed that I'm not seeing?

**Comment by andrew** [comment]
Sounds like a bug, will investigate and report back.
