### ISSUE TITLE
Make @SgtPooki part of "core" (PL EngRes)

### ISSUE THREAD

**Issue by BigLep** [ipfs-shipyard/ecosystem-dashboard#397]
@SgtPooki is part of PL EngRes.  He should show up as "core".

We noticed this in this triage URL: https://ecosystem-research.herokuapp.com/all?org=ipfs&exclude_language%5B%5D=Go&exclude_language%5B%5D=Shell&exclude_language%5B%5D=Makefile&exclude_repo_full_name%5B%5D=ipfs%2Fipfs-companion&exclude_repo_full_name%5B%5D=ipfs%2Fipfs-desktop&exclude_repo_full_name%5B%5D=ipfs%2Fipfs-webui&exclude_repo_full_name%5B%5D=ipfs%2Fpublic-gateway-checker&exclude_repo_full_name%5B%5D=ipfs%2Fipfs-update&exclude_repo_full_name%5B%5D=ipfs%2Fawesome-ipfs&exclude_repo_full_name%5B%5D=ipfs%2Fcommunity&exclude_repo_full_name%5B%5D=ipfs%2Fdevgrants&exclude_repo_full_name%5B%5D=ipfs%2Fecosystem-directory&exclude_repo_full_name%5B%5D=ipfs%2Fipfs&exclude_repo_full_name%5B%5D=ipfs%2Fipfs-docs&exclude_repo_full_name%5B%5D=ipfs%2Fipfs-website&exclude_repo_full_name%5B%5D=ipfs%2Fipfs-blog&exclude_repo_full_name%5B%5D=ipfs%2Fspecs&exclude_repo_full_name%5B%5D=ipfs%2Fnotes&exclude_repo_full_name%5B%5D=ipfs%2Finfra&exclude_repo_full_name%5B%5D=ipfs%2Fipfs-cluster&exclude_repo_full_name%5B%5D=ipfs%2Fpinning-services-api-spec&exclude_repo_full_name%5B%5D=ipfs%2Fdistributions&exclude_repo_full_name%5B%5D=ipfs%2Fdistributed-wikipedia-mirror&exclude_repo_full_name%5B%5D=ipfs%2Fin-web-browsers&exclude_repo_full_name%5B%5D=ipfs%2Ffs-repo-migrations&exclude_repo_full_name%5B%5D=ipfs%2Fbbloom&exclude_repo_full_name%5B%5D=ipfs%2Fipget&exclude_repo_full_name%5B%5D=ipfs%2Fipfs-ds-postgres&exclude_repo_full_name%5B%5D=ipfs%2Fhang-fds&exclude_repo_full_name%5B%5D=ipfs%2Fipfs-ds-convert&range=360&state=open&per_page=100&sort=updated_at&order=desc&no_boards=true&community=true&exclude_core=true&type=pull_requests

**Comment by andrew** [comment]
Done!
