### ISSUE TITLE
Add vulcanize as a collab

### ISSUE THREAD

**Issue by BigLep** [ipfs-shipyard/ecosystem-dashboard#398]
We'd like @i-norden and vulcanize (if there's an organization for them) to be listed as collabs.  

Reference PR https://github.com/ipld/specs/pull/369
Reference dashboard link: https://ecosystem-research.herokuapp.com/all?org=ipld&range=360&state=open&per_page=100&sort=updated_at&order=desc&no_boards=true&community=true&exclude_core=true&type=pull_requests

**Comment by andrew** [comment]
Done! Also made a tweak to update the collabs list when syncing individual issues, especially useful for really old issues like the one referenced there.
