### ISSUE TITLE
When is the "last updated" field updated?

### ISSUE THREAD

**Issue by BigLep** [ipfs-shipyard/ecosystem-dashboard#407]
As part of weekly triage for ipfs/libp2p/ipld, we filter issues/PRs by last updated time (newest first) to make sure we're catching the freshest items.  I find that there are often issues that were created months ago and haven't received any comments, labels, board assignment, etc. for months but they show up as being updated in the last couple of days.  Are there hidden events that are causing these issues/PRs to look fresher than they actually are?

**Comment by andrew** [comment]
Found one spot that could be causing updated_ats to be inconsitent with github, going to resync a good number of issues fix those data points, the order of some of your lists could change whilst this is happening.
