### ISSUE TITLE
Usecase for https://libp2p.ecosystem-dashboard.com vs https://ipfs.ecosystem-dashboard.com/

### ISSUE THREAD

**Issue by BigLep** [ipfs-shipyard/ecosystem-dashboard#414]
Hi @andrew ,

Givent that https://ipfs.ecosystem-dashboard.com/ includes the libp2p organization, what's the intended usecase for https://libp2p.ecosystem-dashboard.com?

Is it correct to assume that any collab/core updates made for https://ipfs.ecosystem-dashboard.com/ don't automatically propagate to https://libp2p.ecosystem-dashboard.com?

Thanks,
Steve

**Comment by andrew** [comment]
The libp2p only dashboard was mostly set up as a test for single-org instances of the ecosystem dashboard, I don't believe it's being used very much and yes collab/core updates are not automatically propagated from ipfs to libp2p.

**Comment by BigLep** [comment]
@andrew : great - good to know.  I'll plan on just having our team use the IPFS instance since it provides a superset of repos and prevents needing to make collab/core metadata updates multiple places.  Closing.
