### ISSUE TITLE
RSS/Atom feeds for all views

### ISSUE THREAD

**Issue by autonome** [ipfs-shipyard/ecosystem-dashboard#50]
Want to feed this to bots, other metrics dashboards, and a variety of other applications.

A generic serialization impl across all views might be a quick route to doing that w/o a lot of custom work.

**Comment by andrew** [comment]
Just deployed rss feed for most pages that make sense (ordered list of things):

- [Issues and Pull Requests]()
- [Issues and Pull Requests]()
- [Issues and Pull Requests]()
- [Issues and Pull Requests]()

**Comment by andrew** [comment]
Pagination is also supported, useful http headers returned for next/prev and total page counts:
![Screenshot 2020-07-09 at 14 16 40](https://user-images.githubusercontent.com/1060/87044696-d3eb1e80-c1ee-11ea-9cdf-a07bdc87ed14.png)

**Comment by andrew** [comment]
You can also swap out `.rss` on the end of those urls with `.json` and a similar result but in json instead of xml:

![Screenshot 2020-07-09 at 14 23 03](https://user-images.githubusercontent.com/1060/87045434-caae8180-c1ef-11ea-9288-78204095461e.png)

**Comment by andrew** [comment]
This is live now on all three instances 🚢

**Comment by autonome** [comment]
THANKYOUTHANKYOU ❤️ JSONJSONJSONTOONICE
