### ISSUE TITLE
can haz option to exclude draft PRs?

### ISSUE THREAD

**Issue by autonome** [ipfs-shipyard/ecosystem-dashboard#52]
eg: https://github.com/ipfs/js-ipfs-utils/pull/45

**Comment by andrew** [comment]
Dupe of https://github.com/ipfs-shipyard/ecosystem-dashboard/issues/48

**Comment by andrew** [comment]
🚢 

![Screenshot 2020-07-09 at 15 56 55](https://user-images.githubusercontent.com/1060/87056521-ac4f8280-c1fd-11ea-80b0-c4601368f89f.png)
