### ISSUE TITLE
libp2p Heroku instance hitting scaling limits

### ISSUE THREAD

**Issue by BigLep** [ipfs-shipyard/ecosystem-dashboard#539]
Hi Andrew,

I'm not sure if you got this email.  (I also didn't see an address I could forward to for you.)

How do you usually handle this?  Buy more capacity?  Drop some of the table?

Steve

---

The database DATABASE_URL on Heroku app libp2p-ecosystem has exceeded its allocated storage capacity. Immediate action is required.

The database contains 10,307,983 rows, exceeding the Basic plan limit of 10,000,000. INSERT privileges to the database will be automatically revoked in 7 days. This will cause service failures in most applications dependent on this database.

To avoid a disruption to your service, migrate the database to a higher plan:

https://elements.heroku.com/addons/heroku-postgresql

For instructions on migrating data to a higher plan database using pg:backups, see:

https://devcenter.heroku.com/articles/updating-heroku-postgres-databases

If you are unable to upgrade the database, you should reduce the number of records stored in it.

**Comment by andrew** [comment]
@BigLep I'm looking into this, if it's easy to drop some data I will, otherwise I'll upgrade it

**Comment by andrew** [comment]
I've significantly reduced the row count by cleaning up some unused data (bot events mostly), not sure exactly how long it'll take heroku to update their count but shouldn't be longer than a day
