### ISSUE TITLE
switch between all / collabs without losing filters

### ISSUE THREAD

**Issue by autonome** [ipfs-shipyard/ecosystem-dashboard#54]
Ok maybe this is overboard, but it's come up repeatedly in triage sessions:

We'll start w/ collabs and add a bunch of filters... and then move to all issues and lose all the filters.

We now have both urls configured and in the triage invite so we're fiiiiiine. But we still end up just changing "collab_issues" to "all" in the url ;)

**Comment by andrew** [comment]
That'll basically happen when https://github.com/ipfs-shipyard/ecosystem-dashboard/issues/42 is done, all/collabs will be the same page with a toggle for "only collabs"

**Comment by andrew** [comment]
![Screenshot 2020-07-21 at 16 11 41](https://user-images.githubusercontent.com/1060/88072630-2f14fd80-cb6d-11ea-80d6-00bac0bba8fc.png)

You can now switch from "all issues+prs" to "only issues+prs opened by collab contributors" from the extras menu, the two pages are now the same, so the url will change (with a legacy redirect that keeps selected filters) but everything should keep working.
