### ISSUE TITLE
Missing "ipfs" org data for the last ~30 days?

### ISSUE THREAD

**Issue by BigLep** [ipfs-shipyard/ecosystem-dashboard#597]
"ipfs" org data is missing for the last ~30 days

30 days - No IPFS data: https://ecosystem-research.herokuapp.com/all?range=30
90 days - there is IPFS data: https://ecosystem-research.herokuapp.com/all?range=90

Do you know what would be causing this @andrew and are you able to help out here?

**Comment by andrew** [comment]
I've found the problem, a dependency update recently caused a silent syncing error, I've rolled back the dependency update and will start resyncing all projects, data will update over the next few hours
