### ISSUE TITLE
ecosystem-research.herokuapp.com is offline

### ISSUE THREAD

**Issue by lidel** [ipfs-shipyard/ecosystem-dashboard#738]
https://ecosystem-research.herokuapp.com is down:

> ![2024-03-19_14-13](https://github.com/ipfs-shipyard/ecosystem-dashboard/assets/157609/51417023-77cd-4875-a303-b3222976bc08)

**Comment by lidel** [comment]
@andrew is it possible the instance got turned off because we did not use it for 2 lat weeks? or some other reason?   (we need the dashboard for for [Kubo / Go  Triage](https://pl-strflt.notion.site/Kubo-Boxo-Go-Issue-Triage-Notes-7d4983e8cf294e07b3cc51b0c60ede9a?pvs=74))

**Comment by andrew** [comment]
It's moved servers off of heroku, the correct domain is https://ipfs.ecosystem-dashboard.com/ al the same paths should still work

**Comment by lidel** [comment]
Thanks! I'll update links we use for triage.
