### ISSUE TITLE
Add Accenture as a collab

### ISSUE THREAD

**Issue by lidel** [ipfs-shipyard/ecosystem-dashboard#744]
@andrew not sure what is the process of adding collabs, so filling an issue. 
Lmk if there is a self-service way (admin panel i can get access to?) so I won't bother you in the future.

We want to create [Accenture](https://en.wikipedia.org/wiki/Accenture) collab with below github handles:
```
smvdn
sushilsaha1111
syed-shamayel
```

**Comment by andrew** [comment]
There's not a dashboard for setting individual users as collabs at the moment, only orgs, I've manually set those three handles as `core`, will add an admin UI if I get time in the next few weeks.
