### ISSUE TITLE
ipfs.ecosystem-dashboard.com is down

### ISSUE THREAD

**Issue by lidel** [ipfs-shipyard/ecosystem-dashboard#811]
Cloudflare fails to reach https://ipfs.ecosystem-dashboard.com origin:

> ![Screenshot 2024-08-14 at 17-22-12 ipfs ecosystem-dashboard com 502 Bad gateway](https://github.com/user-attachments/assets/aef7091c-5793-4bbc-9029-e359cea256ee)

@andrew this seems to be a longer outage, been like this since yesterday

**Comment by andrew** [comment]
Sorry about that, I’m out of office today, will get on it first thing tomorrow morning

**Comment by andrew** [comment]
It's back up now, that'll teach me to not take my laptop when I leave the house for 24 hours, sorry!
